<a href="https://colab.research.google.com/github/67015127/Lab_5/blob/main/Lab5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

รหัสนักศึกษา : 67015127 ชื่อ :วศิน เสริมสุข

Exercise 5.1 ให้เขียน function ชื่อ day_of_year(day, month ,year) โดยมีการคืนค่า คือ day_of_years เป็นวันที่ลำดับที่เท่าใดของปีคริสตศักราช year
ปีที่เป็น Leap Year เดือนกุมภาพันธ์จะมี 29 วัน
ให้สร้างฟังก์ชัน is_leap เพื่อตรวจสอบ leap year แยกออกมา และให้ฟังก์ชัน day_of_year เรียกใช้ is_leap อีกที


In [ ]:

days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

def is_leap(year):

    if (year % 4) == 0 and(year % 100) !=0 or (year % 400)==0 :
        return True
    else:
      return False



def day_of_year(day, month, year):
    sum1 = 0
    for i in range(month):
      sum1 = sum(days_in_month[:month-1])
      sum1 += day
    if is_leap(year) and month > 2:
        sum1 += 1
    return sum1

# Testcases
print("Normal year (2023):")
print(f"1 Jan 2023: {day_of_year(1, 1, 2023)}")  # ควรได้ 1
print(f"1 Feb 2023: {day_of_year(1, 2, 2023)}")  # ควรได้ 32
print(f"1 Mar 2023: {day_of_year(1, 3, 2023)}")  # ควรได้ 60
print(f"31 Dec 2023: {day_of_year(31, 12, 2023)}")  # ควรได้ 365

print("\nLeap year (2024):")
print(f"1 Jan 2024: {day_of_year(1, 1, 2024)}")  # ควรได้ 1
print(f"29 Feb 2024: {day_of_year(29, 2, 2024)}")  # ควรได้ 60
print(f"1 Mar 2024: {day_of_year(1, 3, 2024)}")  # ควรได้ 61
print(f"31 Dec 2024: {day_of_year(31, 12, 2024)}")  # ควรได้ 366

print("\nCentury year, not a leap year (1900):")
print(f"1 Mar 1900: {day_of_year(1, 3, 1900)}")  # ควรได้ 60

print("\nCentury year, leap year (2000):")
print(f"1 Mar 2000: {day_of_year(1, 3, 2000)}")  # ควรได้ 61

print("\nMid-year dates:")
print(f"15 Jun 2023: {day_of_year(15, 6, 2023)}")  # ควรได้ 166
print(f"15 Jun 2024: {day_of_year(15, 6, 2024)}")  # ควรได้ 167 (Leap year)

print("\nLast day of each quarter:")
print(f"31 Mar 2023: {day_of_year(31, 3, 2023)}")  # ควรได้ 90
print(f"30 Jun 2023: {day_of_year(30, 6, 2023)}")  # ควรได้ 181
print(f"30 Sep 2023: {day_of_year(30, 9, 2023)}")  # ควรได้ 273
print(f"31 Dec 2023: {day_of_year(31, 12, 2023)}")  # ควรได้ 365

Normal year (2023):
1 Jan 2023: 1
1 Feb 2023: 32
1 Mar 2023: 60
31 Dec 2023: 365

Leap year (2024):
1 Jan 2024: 1
29 Feb 2024: 60
1 Mar 2024: 61
31 Dec 2024: 366

Century year, not a leap year (1900):
1 Mar 1900: 60

Century year, leap year (2000):
1 Mar 2000: 61

Mid-year dates:
15 Jun 2023: 166
15 Jun 2024: 167

Last day of each quarter:
31 Mar 2023: 90
30 Jun 2023: 181
30 Sep 2023: 273
31 Dec 2023: 365


Exercise 5.2 ให้เขียนฟังก์ชัน เพิ่มเติมเป็น date_diff
รับข้อมูลในรูปแบบ “dd-mm-yyyy” เช่น date_diff(“1-1-2018”, “1-1-2020”) จะได้ 731 วัน date_diff(“25-12-1999”, “9-3-2000”) จะได้ 76 วัน
ให้เขียนฟังก์ชัน day_in_year โดยจะส่งค่าจำนวนวันของปี (365 หรือ 366) โดยรับข้อมูลเป็น ปี
ส่งคืนข้อมูลเป็นจำนวนวันตั้งแต่วันที่แรก จนถึงวันที่สอง โดยรวมทั้ง 2 วันนั้นเข้าไปด้วย
ให้สมมติว่าวันแรก จะต้องมาก่อนวันที่สองเสมอ ดังนั้นไม่ต้องตรวจสอบ


In [ ]:
days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

def is_leap(year):

    if (year % 4) == 0 and(year % 100) !=0 or (year % 400)==0 :
        return True
    else:
      return False

def day_of_year(day, month, year):
      sum1 = 0
      for i in range(month):
        sum1 = sum(days_in_month[:month-1])
        sum1 += day
      if is_leap(year) and month > 2:
        sum1 += 1
      return sum1

def day_in_year(year):
    return 366 if is_leap(year) else 365

def date_diff(date1, date2):
    d1, m1, y1 = map(int, date1.split('-'))
    d2, m2, y2 = map(int, date2.split('-'))
    if d1 ==d2 and m1 == m2:
        if is_leap(y1)==True:
            daysum =  abs(y1-y2)*366
        else:
            daysum =  1+abs(y1-y2)*365
    elif y1!=y2 :
         daysum =  abs(day_of_year(d1, m1, y1)-365)+day_of_year(d2, m2, y2)+1
    elif y1 == y2 :
        daysum = day_of_year(d1, m1, y1)+day_of_year(d2, m2, y2)-1
    return daysum
# ทดสอบฟังก์ชัน
print(date_diff("1-1-2018", "1-1-2020"))  # ควรได้ 731
print(date_diff("25-12-1999", "9-3-2000"))  # ควรได้ 76
print(date_diff("1-1-2000", "1-1-2001"))  # ควรได้ 367 (ปี 2000 เป็น leap year)
print(date_diff("1-1-2001", "1-1-2002"))  # ควรได้ 366 (ปี 2001 ไม่ใช่ leap year)
print(date_diff("1-3-2000", "1-3-2001"))  # ควรได้ 367 (ข้ามปี leap year)
print(date_diff("1-1-2023", "31-12-2023"))  # ควรได้ 365 (ทั้งปี 2023)


731
76
366
366
366
365


Exercise 5.3 จากโปรแกรม 5.2 ให้เขียนฟังก์ชัน date_diff  เพิ่มเติม โดยให้มีการตรวจสอบ
วันที่ต้องเป็นวันที่ถูกต้องของเดือนนั้นๆ
เดือนต้องอยู่ระหว่าง 1-12
เดือนกุมภาพันธ์ของปีที่มี Leap Year เท่านั้นที่จะมี 29 วันได้
หากข้อมูล Input ผิดพลาด ให้ Return -1


In [ ]:
days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
def is_leap(year):
    if (year % 4) == 0 and(year % 100) !=0 or (year % 400)==0 :
        return True
    else:
      return False
def wrong(day, month, year):
   if month < 1 or month > 12:
          return False
   max_days = days_in_month[month - 1]
   if month == 2 and is_leap(year):

        max_days = 29  # Adjust February for leap years
   if day < 1 or day > max_days:
        return False
   return True
def day_of_year(day, month, year):
      sum1 = 0
      for i in range(month):
        sum1 = sum(days_in_month[:month-1])
        sum1 += day
      if is_leap(year) and month > 2:
        sum1 += 1
      return sum1

def day_in_year(year):
    return 366 if is_leap(year) else 365

def date_diff(date1, date2):
    if date1.isalpha()==True :
        return -1
    else:
      d1, m1, y1 = map(int, date1.split('-'))
      d2, m2, y2 = map(int, date2.split('-'))
      if d1 ==29 and days_in_month[1]:
        return -1

      if d1 ==d2 and m1 == m2:
        if is_leap(y1)==True:
            daysum =  1+abs(y1-y2)*366
        else:
            daysum =  1+abs(y1-y2)*365
      elif y1!=y2 :
         daysum =  abs(day_of_year(d1, m1, y1)-365)+day_of_year(d2, m2, y2)+1
      elif y1 == y2 :
        daysum = day_of_year(d1, m1, y1)+day_of_year(d2, m2, y2)-1
      if not wrong(d1, m1, y1) or not wrong(d2, m2, y2):
        return -1
      return daysum

# ทดสอบฟังก์ชัน
print(date_diff("1-1-2018", "1-1-2020"))  # ควรได้ 731
print(date_diff("25-12-1999", "9-3-2000"))  # ควรได้ 76
print(date_diff("1-1-2000", "1-1-2001"))  # ควรได้ 367 (ปี 2000 เป็น leap year)
print(date_diff("1-1-2001", "1-1-2002"))  # ควรได้ 366 (ปี 2001 ไม่ใช่ leap year)
print(date_diff("1-3-2000", "1-3-2001"))  # ควรได้ 367 (ข้ามปี leap year)
print(date_diff("1-1-2023", "31-12-2023"))  # ควรได้ 365 (ทั้งปี 2023)

# ทดสอบกรณีข้อมูลไม่ถูกต้อง
print(date_diff("31-4-2023", "1-5-2023"))  # ควรได้ -1 (เดือนเมษายนมี 30 วัน)
print(date_diff("29-2-2023", "1-3-2023"))  # ควรได้ -1 (ปี 2023 ไม่ใช่ leap year)
print(date_diff("1-13-2023", "1-1-2024"))  # ควรได้ -1 (เดือนไม่ถูกต้อง)
print(date_diff("abc", "1-1-2024"))  # ควรได้ -1 (รูปแบบวันที่ไม่ถูกต้อง)

731
76
367
366
367
365
-1
-1
-1
-1


1.	ปลาหมอคางดำเพศเมีย 1 ตัว เมื่ออายุครบ 2 เดือน จะสามารถสืบพันธ์ได้ โดยระยะเวลาตั้งท้องจนถึง
วางไข่ของตัวเมียจะใช้เวลา 21 วัน และฟักในปากเพศผู้อีก 7 วัน (สามารถรวมเป็น 1 เดือนได้) โดยออกไข่ครั้งละ 300 ฟอง กำหนดให้ไข่ฟักเป็นเพศผู้และเพศเมียอย่างละครึ่ง และเมื่อวางไข่แล้วจะสามารถสืบพันธ์ต่อได้ทันที กำหนดให้ปลามีอายุ 5 ปี และปลาทั้งหมดจะตาย p% ทุก 1 เดือน จงหาว่าปลาหมอคางดำหลุดจากฟาร์ม n ตัวเป็นเพศผู้และเพศเมียอย่างละครึ่ง จงเขียนโปรแกรมรับค่า n และ p ให้แสดงผลจำนวนปลาทุก 3 เดือน เป็นเวลา 10 ปี ให้เขียนเป็นฟังก์ชัน ชื่อ simulate_fish_population()


In [ ]:
import math

def simulate_fish_population(n, p, month=3):
    deadtime = 5 * 12
    rounds = month // 3
    monthcount = 0
    fish_count_month = []
    for i in range(int(rounds)):
        if monthcount >= deadtime:
            n -= fish_count_month.pop(0)
        # ไข่
        egg_fish = (n / 2) * 300
        monthcount += 1
        if monthcount >= deadtime:
            n -= fish_count_month.pop(0)
        fish_count_month.append(n)
        # ปลาเล็ก
        baby_fish = egg_fish * (1 - p / 100)
        monthcount += 1

        if monthcount >= deadtime:
            n -= fish_count_month.pop(0)
        fish_count_month.append(n)
        #ปลาใหญ่
        big_fish = baby_fish * (1 - p / 100)
        monthcount += 1

        print(f'Month: {monthcount}, Eggs: {int(egg_fish)}, Baby Fish: {int(baby_fish)}, '
              f'Adult Fish: {int(big_fish)}, Total: {int(n + baby_fish + big_fish)}')

        n = big_fish + n
        fish_count_month.append(n)
    return egg_fish, baby_fish, big_fish
month = 10 * 12
n = 2
p = 10
simulate_fish_population(n, p, month)

Month: 3, Eggs: 300, Baby Fish: 270, Adult Fish: 243, Total: 515
Month: 6, Eggs: 36750, Baby Fish: 33075, Adult Fish: 29767, Total: 63087
Month: 9, Eggs: 4501875, Baby Fish: 4051687, Adult Fish: 3646518, Total: 7728218
Month: 12, Eggs: 551479687, Baby Fish: 496331718, Adult Fish: 446698546, Total: 946706796
Month: 15, Eggs: 67556261718, Baby Fish: 60800635546, Adult Fish: 54720571992, Total: 115971582617
Month: 18, Eggs: 8275642060546, Baby Fish: 7448077854492, Adult Fish: 6703270069042, Total: 14206518870605
Month: 21, Eggs: 1013766152416992, Baby Fish: 912389537175293, Adult Fish: 821150583457763, Total: 1740298561649170
Month: 24, Eggs: 124186353671081552, Baby Fish: 111767718303973392, Adult Fish: 100590946473576048, Total: 213186573802023296
Month: 27, Eggs: 15212828324707487744, Baby Fish: 13691545492236738560, Adult Fish: 12322390943013064704, Total: 26115355290747854848
Month: 30, Eggs: 1863571469776667017216, Baby Fish: 1677214322799000420352, Adult Fish: 150949289051910045696

(8.211617546504697e+83, 7.390455791854228e+83, 6.651410212668806e+83)

2.	ให้เขียน function find_mismatch ซึ่งรับ string มา 2 ค่า โดยจะส่งค่ากลับดังนี้
- 0 เมื่อ string ทั้ง 2 ตัว เหมือนกัน โดยไม่สนใจ case
- 1 เมื่อ string 1 จะเหมือน string 2 โดยการลบและ/หรือเพิ่มตัวอักษรเพียง 1 ตัว
- 2 เมื่อ string ไม่เข้าเกณฑ์ 0 หรือ 1


| String  1| 	String2	|ผลลัพธ์|
|----------|----------|------|
|Python|	Java	|2|
|book	 |  boot	|1|
|fan	 |  fun	  |1|
|sin	 | sink	  |1 เพราะเพิ่ม k ใน str2 แล้วจะเหมือนกัน
|Dog	 | dog	  |0
|poke	 | spoke	|1 เพิ่ม s ใน str2 แล้วเหมือนกัน
|poker |	poke	|1 ตัด r ใน str1 ออกแล้วเหมือนกัน






In [ ]:
def find_mismatch(str1, str2):
    str1 = str1.lower()
    str2 = str2.lower()

    if str1 == str2:
        return 0

    len1, len2 = len(str1), len(str2)
    if abs(len1 - len2) > 1:
        return 2

    i, j = 0, 0
    found_difference = False

    while i < len1 and j < len2:
        if str1[i] != str2[j]:
            if found_difference:
                return 2
            found_difference = True
            if len1 > len2:
                i += 1
            elif len1 < len2:
                j += 1
            else:
                i += 1
                j += 1
        else:
            i += 1
            j += 1

    return 1
print(find_mismatch('Python', 'Java'))
print(find_mismatch('book', 'boot'))
print(find_mismatch('fan', 'fun'))
print(find_mismatch('sin', 'sink'))
print(find_mismatch('Dog', 'dog'))
print(find_mismatch('spoke', 'poke'))
print(find_mismatch('poker', 'poke'))

2
1
1
1
0
1
1


3.	จากข้อ 1 ให้เขียนฟังก์ชันชื่อ spelling_correction โดยรับ 2 argument ตัวแรกเป็นประโยค (string) และตัวที่ 2 เป็น list ของคำ (correct_spells) โดยฟังก์ชันนี้มีหน้าที่ตรวจสอบแต่ละ word ใน input string กับคำที่อยู่ใน correct_spells โดยค่าที่คืนกลับมาจะมีดังนี้ (พยายามเรียกใช้ฟังก์ชันในข้อ 1)
-	ถ้าคำที่อยู่ในประโยค ตรงกับคำที่อยู่ใน correct_spells ทุกอย่าง ก็จะ copy ไปที่ output string
-	ถ้าคำที่อยู่ในประโยค ต่างจากคำที่อยู่ใน correct_spells โดยต่างกัน 1 ตัวอักษร โดยการเปลี่ยน การเพิ่ม หรือการลบ 1 ตัวอักษร คำที่อยู่ในประโยคจะถูกเปลี่ยนโดยคำที่อยู่ใน correct_spells และนำไปใส่ output string
-	ถ้าคำที่ไม่พบในเงื่อนไขข้างต้นให้นำคำนั้นไปใส่ output string ได้เลย
-	คำที่ประกอบด้วย 1 หรือ 2 ตัวอักษรจะไม่ตรวจสอบ ให้นำคำนั้นไปใส่ output string ได้เลย
-	ถ้ามี 2 คำใน correct_spells ที่ตรงตามเงื่อนไข ให้ใช้คำแรก
-	ไม่สนใจตัวใหญ่ ตัวเล็ก
-	Input string จะมีได้เพียงอักษรภาษาอังกฤษเท่านั้น
-	ในแต่ละคำจะคั่นด้วย 1 space ถ้ามี space มากกว่านั้นให้ตัดออก และตัด space จากหัวท้ายประโยค

|ประโยค	|correct_spells	|output string |
|-------|---------------|-------------|
|Thes is the Firs cas	|[‘that’,’first’,’case’,’car’]|	thes is the first car|
|programming is fan and easy	|[‘programming’,’this’,’fun’,’easy’,book’]	|programming is fun and easy|
|Thes is vary essy	|[‘this’,’is’,’very’,’easy’]	|this is very easy|
|Wee ipve Pythen	|[‘we’,’live’,’ln’,’Python’]	|we live python|




In [ ]:
def find_mismatch(str1, str2):
    str1 = str1.lower()
    str2 = str2.lower()

    if str1 == str2:
        return 0

    len1, len2 = len(str1), len(str2)
    if abs(len1 - len2) > 1:
        return 2

    i, j = 0, 0
    found_difference = False

    while i < len1 and j < len2:
        if str1[i] != str2[j]:
            if found_difference:
                return 2
            found_difference = True
            if len1 > len2:
                i += 1
            elif len1 < len2:
                j += 1
            else:
                i += 1
                j += 1
        else:
            i += 1
            j += 1

    return 1 if found_difference else 0

def spelling_correction(input_string, correct_spells):
    input_words = input_string.split()
    corrected_words = []
    for word in input_words:
        best_match = word
        min_mismatch = len(word) + 1
        for correct in correct_spells:
            mismatches = find_mismatch(word, correct)
            if mismatches < min_mismatch:
                best_match = correct
                min_mismatch = mismatches
            elif mismatches == min_mismatch and len(correct) == len(word):
                best_match = correct
        corrected_words.append(best_match)
    return " ".join(corrected_words)
print(spelling_correction("Thes is the Firs cas", ['that', 'first', 'case', 'car']))
print(spelling_correction("programming is fan and easy", ['programming', 'this', 'fun', 'easy', 'book']))
print(spelling_correction("Thes is vary essy", ['this', 'is', 'very', 'easy']))
print(spelling_correction("Wee ipve Pythen", ['we', 'live', 'In', 'Python']))

case that car first case
programming programming fun fun easy
this is very easy
we live Python


4. ให้เขียนฟังก์ชัน find_word_horizontal ซึ่งจะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตามแถวของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบ จะส่งคืน row index และ column index ของตัวอักษรแรก ถ้าไม่พบจะส่งคืน None

```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','c','a','t'],
            ['t',' e','t','k']]
	word='cat'
	find_word_horizontal(crosswords,word)
```

Output
   [2,1]


In [29]:
def find_word_horizontal(crosswords, word):
      row_index = 0
      for row in crosswords:
        row_string = ''.join(row)
        col_index = row_string.find(word)
        if col_index != -1:
            return (row_index, col_index)
        row_index += 1
      return None
crosswords = [['s','d','o','g'],
              ['c','u','c','m'],
              ['a','c','a','t'],
              ['t','e','t','k']]
word = 'cat'
result = find_word_horizontal(crosswords, word)
print(result)

(2, 1)


5. ให้เขียนฟังก์ชัน find_word_vertical ซึ่งจะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตามคอลัมน์ของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบ จะส่งคืน row index และ column index ของตัวอักษรแรก ถ้าไม่พบจะส่งคืน None

ตัวอย่าง
```
	crosswords=[['s','d','o','g'],
              ['c','u','c','m'],
              ['a','c','a','t'],
              ['t',' e','t','k']]
	word='cat'
	find_word_vertical(crosswords,word)
```

Output
   [1,0]


In [ ]:
def find_word_vertical(crosswords, word):
    num_rows = len(crosswords)
    num_cols = len(crosswords[0])
    for col in range(num_cols):
        col_string = ''.join([crosswords[row][col] for row in range(num_rows)])
        row_index = col_string.find(word)
        if row_index != -1:
            return [row_index, col]
    return None
crosswords = [['s','d','o','g'],
              ['c','u','c','m'],
              ['a','c','a','t'],
              ['t','e','t','k']]
word = 'cat'
result = find_word_vertical(crosswords, word)
print(result)

[1, 0]


6.	ให้เขียนฟังก์ชัน capitalize_word_in_crossword จะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตาม row และ column ของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบจะเปลี่ยนเป็นตัวใหญ่และ และส่งคืน list ที่แก้ไขแล้ว แต่ถ้าไม่เจอจะส่ง list เดิมกลับมา ให้ใช้ฟังก์ชันตามข้อ 3 และ 4 ช่วย

```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','x','a','t'],
            ['t','e','t','k']]
word='cat'
capitalize_word_in_crossword(crosswords,word)
```
จะส่งค่ากลับ
```
 [['s','d','o','g'],
  ['C','u','c','m'],
  ['A','x','a','t'],
  ['T','e','t','k']]
```
```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','c','a','t'],
            ['t','e','t','k']]
word='cat'
capitalize_word_in_crossword(crosswords,word)
จะส่งค่ากลับ                   
[['s','d','o','g'],
 ['c','u','c','m'],
 ['a','C','A','T'],
 ['t','e','t','k']]
```




In [30]:
def find_word_horizontal(crosswords, word):
      row_index = 0
      for row in crosswords:
        row_string = ''.join(row)
        col_index = row_string.find(word)
        if col_index != -1:
            return (row_index, col_index)
        row_index += 1
      return None
      pass
def capitalize_word_in_crossword_Horizontal(crosswords, word):
    position= find_word_horizontal(crosswords,word)
    row,col=position
    for i in range(len(word)):
        crosswords[row][col+i] = crosswords[row][col+i].upper()
    return(crosswords)
    pass
crosswords = [
    ['s', 'd', 'o', 'g'],
    ['a', 'u', 'a', 'm'],
    ['a', 'c', 'a', 't'],
    ['t', 'e', 't', 'k']
]
word = 'cat'
if(find_word_horizontal(crosswords,word) != None):
    result = capitalize_word_in_crossword_Horizontal(crosswords, word)
    for i in range(len(result[0])):
        print(result[i])
else:
    for i in range(len(crosswords[0])):
        print(crosswords[i])
def find_word_vertical(crosswords, word):
    num_rows = len(crosswords)
    num_cols = len(crosswords[0])

    for col in range(num_cols):
        col_string = ''.join([crosswords[row][col] for row in range(num_rows)])
        row_index = col_string.find(word)
        if row_index != -1:
            return [row_index, col]
    return None
    pass
def capitalize_word_in_crossword_Vertical(crosswords, word):
    position= find_word_vertical(crosswords,word)
    row,col=position
    for i in range(len(word)):
        crosswords[row+i][col] = crosswords[row+i][col].upper()
    return(crosswords)
    pass
crosswords = [
    ['s', 'd', 'o', 'g'],
    ['c', 'u', 'c', 'm'],
    ['a', 'c', 'a', 't'],
    ['t', 'e', 't', 'k']
]
word = 'cat'
if(find_word_vertical(crosswords,word) != None):
    result = capitalize_word_in_crossword_Vertical(crosswords, word)
    for i in range(len(result[0])):
        print(result[i])
else:
    for i in range(len(crosswords[0])):
        print(crosswords[i])

['s', 'd', 'o', 'g']
['a', 'u', 'a', 'm']
['a', 'C', 'A', 'T']
['t', 'e', 't', 'k']
['s', 'd', 'o', 'g']
['C', 'u', 'c', 'm']
['A', 'c', 'a', 't']
['T', 'e', 't', 'k']
